### ISSUE TITLE
Issue connecting to tracker

### ISSUE THREAD

**Issue by jakefb** [feross/webtorrent-hybrid#1]
When I try seed a torrent using the command line, I get the error: connection error to wss://tracker.webtorrent.io. The normal webtorrent client connects to the tracker, so it shouldn't be offline.

**Comment by feross** [comment]
Not sure why you're getting this error. Sometimes websocket connections are blocked by routers or firewalls. Try again on a different network.

If you can't get this test page to work, then your network is blocking websockets: https://www.websocket.org/echo.html
