### ISSUE TITLE
Connecting from browser to both TCP/UDP peers and WebRTC (browser) peers

### ISSUE THREAD

**Issue by isikfsc** [feross/webtorrent-hybrid#12]
In the README.md of this repo, in node.js, webtorrent no longer connects to WebRTC peers, just normal TCP/UDP peers. If you want to connect to all types of peers, including WebRTC peers, from node.js, you need to use this package (webtorrent-hybrid).

What about from connections browser;
Do modules webtorrent and/or webtorrent-hybrid connect from browser to both TCP/UDP peers and WebRTC (browser) peers?

This was not clear to me from the docs.

**Comment by rom1504** [comment]
Js script that run in the browser cannot connect to TCP/UDP peers, that's why webtorrent exists and make it possible for browser peer to use WebRTC to torrent.

So browser peers (using webtorrent or webtorrent-hybrid) only connect to WebRTC peers.

**Comment by isikfsc** [comment]
Ok, I have thought of a motivation about filling gaps between the two worlds of torrents; TCP/UDP and browser. But the same api seems more of a key point in the webtorrent.

But still it supports one of the two cross lines between two worlds (from TCP/UDP to browsers and reverse).

Thanks.

**Comment by isikfsc** [comment]
Then what about a browser downloading files with torrents, once having a magnet link or other torrent info compatible?

**Comment by rom1504** [comment]
"Then what about a browser downloading files with torrents, once having a magnet link, torrent file or other torrent info compatible?"
yes that's what webtorrent provide, and https://instant.io/ is an example of usage in the browser (the files still need to be seeded in webrtc though)

**Comment by jeancode** [comment]
> Ok, he pensado en una motivación para llenar las brechas entre los dos mundos de torrents; TCP / UDP y navegador. Pero la misma api parece más un punto clave en el webtorrent.
> 
> Pero aún es compatible con una de las dos líneas cruzadas entre dos mundos (desde TCP / UDP a los navegadores y viceversa).
> 
> Gracias.

interesante me parece genial creo que  websocket  + servidor websocket traductor  udp/tcp = websocket + clasico torrent  in web
