### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by acidhax** [feross/webtorrent-hybrid#13]
In file included from ../../webrtc/base/iosfilesystem.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: error: expected a type
- (id)copyWithZone:(nullable NSZone *)zone;
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:25:28: error: expected a type
- (id)mutableCopyWithZone:(nullable NSZone *)zone;
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:32:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder; // NS_DESIGNATED_INITIALIZER
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:53:4: error: expected a type
- (nullable id)replacementObjectForCoder:(NSCoder *)aCoder;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:54:4: error: expected a type
- (nullable id)awakeAfterUsingCoder:(NSCoder *)aDecoder NS_REPLACES_RECEIVER;
   ^
In file included from ../../webrtc/base/iosfilesystem.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSRange.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:17:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:30:42: error: expected a type
+ (NSValue *)valueWithNonretainedObject:(nullable id)anObject;
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:31:12: error: unknown property attribute 'nullable'
@property (nullable, readonly) id nonretainedObjectValue;
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:33:32: error: expected a type
+ (NSValue *)valueWithPointer:(nullable const void *)pointer;
                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:34:12: error: unknown property attribute 'nullable'
@property (nullable, readonly) void *pointerValue;
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:42:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:81:38: error: expected a type
- (NSString *)descriptionWithLocale:(nullable id)locale;
                                     ^
In file included from ../../webrtc/base/iosfilesystem.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:23: error: expected ';' after @class
@class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:24: error: cannot find protocol declaration for 'ObjectType'
@class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:35: error: expected unqualified-id
@class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:82:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:109:123: error: expected a type
- (NSComparisonResult)compare:(NSString *)string options:(NSStringCompareOptions)mask range:(NSRange)compareRange locale:(nullable id)locale; // locale arg used to be a dictionary pre-Leopard. We now accept NSLocale. Assumes the current locale if non-nil and non-NSLocale. nil continues to mean canonical compare, which doesn't depend on user's locale choice.
                                                                                                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:147:123: error: expected a type
- (NSRange)rangeOfString:(NSString *)searchString options:(NSStringCompareOptions)mask range:(NSRange)searchRange locale:(nullable NSLocale *)locale NS_AVAILABLE(10_5, 2_0);
                                                                                                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:151:37: error: expected a type
- (NSRange)rangeOfCharacterFromSet:(NSCharacterSet *)searchSet;
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[448/630] CXX obj/webrtc/system_wrappers/source/system_wrappers.sort.o
ninja: build stopped: subcommand failed.
ERROR: 1 null 

make: *** [/dev/null] Error 255
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/mat/.nvm/versions/node/v4.1.2/bin/node" "/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.58/Release/node-v46-darwin-x64/wrtc.node" "--module_name=wrtc" "--module_path=/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.58/Release/node-v46-darwin-x64"
gyp ERR! cwd /Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/mat/.nvm/versions/node/v4.1.2/bin/node /Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.58/Release/node-v46-darwin-x64/wrtc.node --module_name=wrtc --module_path=/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.58/Release/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/Users/mat/.nvm/versions/node/v4.1.2/bin/node" "/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc
node-pre-gyp ERR! node -v v4.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/Users/mat/.nvm/versions/node/v4.1.2/bin/node /Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.58/Release/node-v46-darwin-x64/wrtc.node --module_name=wrtc --module_path=/Users/mat/dev/video-encoder/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.58/Release/node-v46-darwin-x64' (1)
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/mat/.nvm/versions/node/v4.1.2/bin/node" "/Users/mat/.nvm/versions/node/v4.1.2/bin/npm" "install" "webtorrent-hybrid"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.58 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.58 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mat/dev/video-encoder/npm-debug.log

https://gist.github.com/acidhax/0b3b5dbe59b9a19dd1d1

**Comment by rom1504** [comment]
https://github.com/js-platform/node-webrtc/pull/229

**Comment by DiegoRBaquero** [comment]
Having the same issue. I have tried node 0.10, 0.12 and 4.1

Still can't get to install it.

**Comment by ericwooley** [comment]
I got it under ubuntu with node 0.10.x, but I don't want to use that version of node. Hopefully webrtc gets fixed. @feross Have you looked into this at all? It seems that webtorrent hybrid is getting a bit out of date.

**Comment by jsindy** [comment]
I couldn't get it working in node 0.10, 0.12, 4.1 or 5.1.

**Comment by jsindy** [comment]
@ericwooley how did you get past "npm ERR! not a package /tmp/npm-5-M6AlQmVz/github.com/jhiesey/mp4box.js.git" on node 0.10?

**Comment by jsindy** [comment]
Heres my Dockerfile from testing

FROM ubuntu:14.04.3
RUN apt-get update
RUN apt-get -y install vim git curl wget python build-essential
RUN curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash - #NODE 0.10
#RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - #NODE 4
#RUN curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash - #NODE 0.12
#RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - #NODE 5
RUN apt-get -y install nodejs
RUN npm install webtorrent-hybrid -g
CMD webtorrent-hybrid

**Comment by ericwooley** [comment]
@jsindy I am not really sure, I installed in on my desktop/fileserver. and I was suprised to see it work. Ill try to reproduce in a docker.

as for mp4box, I don't get past that error if I am using npm@2

**Comment by ericwooley** [comment]
@jsindy It doesn't work in docker, but I started up a digital ocean box with ubuntu 15.x and install nvm 0.10, 
```
npm install -g npm@2
# from docs in https://github.com/js-platform/node-webrtc
sudo apt-get install python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev
npm install -g webtorrent-hybrid
```

It might work in node 0.12.7 as well, haven't tried it yet. It seems that the real issue was docker though.

**Comment by ericwooley** [comment]
I also got it to work in yosemite this way the same way.

On ubuntu it seems to be working with 0.12.7, but not yosemite, only 0.10 works there. 

I'll check el capitan when I get home.

**Comment by DiegoRBaquero** [comment]
El capitan might work if you have XCode 6.x

Couldn't get it to work in 7

**Comment by jsindy** [comment]
Working Dockerfile

FROM ubuntu:15.04
RUN apt-get update
RUN apt-get -y install vim git curl wget python build-essential sudo
RUN curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash - #NODE 0.10
RUN apt-get -y install python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev
RUN apt-get -y install nodejs
RUN npm install node-gyp@latest
RUN npm install -g npm@2
RUN npm install wrtc
RUN npm install -g webtorrent-hybrid --unsafe-perm
CMD webtorrent-hybrid

**Comment by jsindy** [comment]
Working Dockerfile

FROM ubuntu:15.04
RUN apt-get update
RUN apt-get -y install vim git curl wget python build-essential sudo
RUN curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash - #NODE 0.10
RUN apt-get -y install python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev
RUN apt-get -y install nodejs
RUN npm install node-gyp@latest
RUN npm install -g npm@2
RUN npm install wrtc
RUN npm install -g webtorrent-hybrid --unsafe-perm
CMD webtorrent-hybrid

**Comment by ericwooley** [comment]
Maybe add that dockerfile as a pull request?

**Comment by feross** [comment]
This issue can be closed now that `webtorrent-hybrid` is based on Electron instead of `wrtc`, as of 1.0.0.
