### ISSUE TITLE
Webtorrent-hybrid nevers ends file download

### ISSUE THREAD

**Issue by brusacco** [feross/webtorrent-hybrid#14]
Hello,
I have webtorent-hybrid running on a torrent file, but it never ends downloading it.
The file size is 851.33MB, every time the console size gets at 831.33, it goes back to 849MB ... any ideas about this? ... Also sometimes it just hangs, have to kill the console and open another one.

I'll give more details if needed. Using nvm.

Thanks.

**Comment by DiegoRBaquero** [comment]
What node & npm version are you using?

I can't even install the client because of wrtc installation fails.

**Comment by brusacco** [comment]
Hi, sorry for the delay. I'll check, but was a long fight to get it installed.
Now it downloaded the hole file, after a restart. But it gets hang very often. Also when seeding a file, it gets hang.

**Comment by brusacco** [comment]
Node - v0.12.7
npm - 2.11.3

**Comment by brusacco** [comment]
You should install 1st. wrtc in node ... then go for webtorrent-hybrid, justo to separate the problems. :)

**Comment by DiegoRBaquero** [comment]
I got it all working. Thanks man. I downloaded a BT Torrent and it worked just fine. Is the torrent you are trying to download a TCP/UDP one or WebRTC one?

**Comment by brusacco** [comment]
A TCP/UDP one, and many web ones using it as it download the torrent file.
Great you got it working ....!

**Comment by DiegoRBaquero** [comment]
What about the ram usage? I had that issue when I tried in a 768MB VPS. When I moved to 2GB one it worked fined.

**Comment by brusacco** [comment]
I'm running it in a local Ubuntu box, 16GB ram. Chrome crashes too, many
times when downloading the torrents. Big files 1GB+

**Comment by feross** [comment]
@brusacco Can you try downloading the same torrent file in `webtorrent` and see if it works? This will help isolate if the issue is caused by `webtorrent-hybrid` or something else.

```
npm install webtorrent -g
webtorrent download "magnet_uri"
```

**Comment by brusacco** [comment]
Webtorrent have no problems, but I have to test again webtorrent-hybrid,
long time not using it! :)

**Comment by feross** [comment]
`webtorrent-hybrid` will probably still have problems until it's rewritten to use electron-spawn #5

**Comment by Stiveknx** [comment]
@feross Is there any plans to do that soon?
My knowledge in Node.js is to small to do that change, I would help if I could ...
