### ISSUE TITLE
Can't download file seeded by libtorrent

### ISSUE THREAD

**Issue by kimtn-bitmark** [feross/webtorrent-hybrid#19]
Hi,
Thanks for great project.

I am using `libtorrent-nodewrap` to seed file (see [libtorrent](http://www.libtorrent.org/examples.html#simple-client) and [libtorrent-nodewrap](https://github.com/bitmark-inc/libtorrent-nodewrap) ). And I can download the file seeded by `libtorrent` (see `download-file-libtorrent.js` in my sample). But i can't download with `webtorrent-hybrid` (see `download-file-webtorrent-hybrid.js` in my sample). 

Is there any way to download file from `libtorrent` via `webtorrent-hybrid` or i make mistake somewhere when config for `webtorrent-hybrid`?

Here is the sample code
[https://github.com/kimtn-bitmark/demo-webtorrent-hybrid-libtorrent](https://github.com/kimtn-bitmark/demo-webtorrent-hybrid-libtorrent)

**Comment by jdoig** [comment]
Are you running that webtorrent-hybrid script in the browser or in node?
I believe it only works with non WebRTC torrent if run from node:

from: https://github.com/feross/webtorrent
> To seed files to web peers, use a client that supports WebTorrent, e.g. webtorrent-hybrid or instant.io.

**Comment by feross** [comment]
@jdoig is correct. In the browser, you can only download from clients that support WebRTC. So, if you're seeding from libtorrent, you'll need to download from webtorrent in node.js.
