### ISSUE TITLE
error can not install on 32-bit 

### ISSUE THREAD

**Issue by zoudf** [feross/webtorrent-hybrid#2]
Hi Feross
I can't install on 32-bit both:
Ubuntu 14.04.2 / Raspberry PI 2  (RASPBIAN) Debin 7.8
but It works well at 64-bit Ubuntu 14.04.2

Log:
pi@raspberrypi ~ $ webtorrent -v
0.47.1
pi@raspberrypi ~ $ sudo npm install -g webtorrent-hybrid
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.10.38","npm":"1.4.28"})
\
> utf-8-validate@1.1.0 install /usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.1.0 install /usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
 attempting to reinstall using temporary dev dir "/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil/build'
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream

> dtrace-provider@0.4.0 install /usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/chromecast-js/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

\
> wrtc@0.0.55 install /usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/.node-gyp"
make: Entering directory '/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build'
make: *** No rule to make target '../.node-gyp/0.10.38/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v11-linux-arm/wrtc.node" "--module_name=wrtc" "--module_path=/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v11-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v11-linux-arm/wrtc.node --module_name=wrtc --module_path=/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.18.11-v7+
node-pre-gyp ERR! command "node" "/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc
node-pre-gyp ERR! node -v v0.10.38
ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v11-linux-arm/wrtc.node --module_name=wrtc --module_path=/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v11-linux-arm' (1)
npm ERR! wrtc@0.0.55 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.0.55 install script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "webtorrent-hybrid"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
pi@raspberrypi ~ $

**Comment by feross** [comment]
This looks like an issue with the `wrtc` module. They only do prebuilt binaries for 64 bit platforms, so you need to make sure you have all the build dependencies installed first.

https://github.com/js-platform/node-webrtc/issues/129
https://github.com/js-platform/node-webrtc#prerequisites
