### ISSUE TITLE
webtorrent-hybrid SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by webarthur** [feross/webtorrent-hybrid#30]
Terminal:
$ nodejs webtorrent.js 

Script:
```
var Xvfb = require('xvfb')
var xvfb = new Xvfb()
xvfb.startSync()

var WebTorrent = require('webtorrent-hybrid')

var client = new WebTorrent()

// When user drops files on the browser, create a new torrent and start seeding it!
client.seed('tor-lol2', function (torrent) {
  console.log('Client is seeding:', torrent.infoHash)
})
```

Output:
```
/home/tutz/Videos/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/node_modules/electron-eval/index.js:19
class Daemon extends EventEmitter {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tutz/Videos/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/index.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Why? =[

**Comment by Autarc** [comment]
This is probably an issue related to the node version used for the execution. Can you tell us which one you are using (see `node --version`) ? The error points to `Class`es which are [a ES2015 feature and not supported in all environments](http://node.green/#class).

@mappum:
Guess the [electron-eval](https://github.com/mappum/electron-eval) module should probably either reference transpiled source code via the `main` field for older setups or explicitly require an `engine` above 5.X. What do you prefer ?

**Comment by mappum** [comment]
@autarc I'll setup Babel transpilation. There's a setup I'm happy with which I use in other repos where it transpiles on npm publish, and uses a symlink to the es6 source while developing.

**Comment by mappum** [comment]
Node <4 support is now enabled as of `electron-webrtc@0.2.3`.

**Comment by webarthur** [comment]
v0.10.25

**Comment by mappum** [comment]
@webarthur Try reinstalling the dependencies (`rm -r node_modules && npm i`) and it should now support your version of Node. BTW, you may also want to consider using a newer version of Node (see [nvm](https://github.com/creationix/nvm) for a convenient way to update).

**Comment by webarthur** [comment]
Ok, I have updated nodejs:
```
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Terminal:
```
$ nodejs webtorrent.js 
sleep: using busy loop fallback
Client is seeding: f11ba044326c18d8c62b7c6d19ba1005d903207b
```

And in browser (https://instant.io/#f11ba044326c18d8c62b7c6d19ba1005d903207b) works! Looks great!

I will put it to work on a digitalocean ubuntu server, there is a documentation for this?

Thanks!

**Comment by feross** [comment]
Node less older than v4 will be deprecated by the end of 2016. You should upgrade!
