### ISSUE TITLE
Possible WebRTC implementation

### ISSUE THREAD

**Issue by somebody1234** [feross/webtorrent-hybrid#32]
https://chromium.googlesource.com/external/webrtc/

https://webrtc.org/native-code/development/

Apparently, Google has a WebRTC implementation on a seperate Git repo. Could this be used as an alternative implementation for less overhead?

**Comment by feross** [comment]
Yeah, that implementation is what [`wrtc`](https://www.npmjs.com/package/wrtc) was using, but it was actually really heavy-weight to compile from source, so we switched to electron which has good prebuilts for all platforms.
