### ISSUE TITLE
Show Electron window/expose Electron window/pass to initializer

### ISSUE THREAD

**Issue by somebody1234** [feross/webtorrent-hybrid#33]
Since it looks like Electron will be needed for a while still, would it be possible to let anything using it use/pass an Electron window if it is needed to reduce overhead?

**Comment by feross** [comment]
How would that reduce overhead? There's only one Electron window created when `webtorrent-hyrbid` is required.

**Comment by Skeen** [comment]
Assuming you're already using one, then reusing that for `webtorrent-hybrid`, instead of having one for each. @feross, but I'm just guessing.

**Comment by feross** [comment]
@Skeen Yeah, that would make sense.

@somebody1234 If you can convince @mappum to support this in `electron-webrtc` (consider sending a PR!) then I'm happy to pass through the option to that package.
