### ISSUE TITLE
instant.io unable to download torrent seeded by webtorrent-hybrid

### ISSUE THREAD

**Issue by FinnFrotscher** [feross/webtorrent-hybrid#34]
Hi Feross
my app is going places but I ran into two issues. One is related to this package. I use it on an `digital-ocean ubuntu node express server`  to seed some files. Which works fine when I want to download the torrent via the `webtorrent` package in an `electron` environment. But when the only seed is the `webtorrent-hybrid ubuntu server` and I drop the `magnetURI` into `instant.io` nothing is found. Once I drop the same magnet into my `electron` app, it finds the torrent, downloads, seeds and THEN the `instant.io` app finds the torrent and downloads it. I assume the problem is that the server doesn't provide `webRTC` connections and `instant.io` accepts only those, which are provided once my `electron` app seeds. 

I have downloaded `xvfb` and installed it via apt-get onto my server and do the whole node routine when the server launches.

    var Xvfb = require('xvfb')
    var xvfb = new Xvfb()
    xvfb.startSync()
    var express = require('express')
    var WebTorrent = require('webtorrent-hybrid');

    client.seed(file.localDir, function onSeed(torrent){
        db.update({_id: file._id}, {$set: {magnetURI: torrent.magnetURI}}, {}, function(err, updates) {
          if(err){console.log(err); throw new Error}
          console.log(updates)
        })
     })

**Comment by feross** [comment]
This sounds like a firewall issue. Are all the ports on your server open? Can you paste the output of `sudo iptables -L` here?

There's no guarantee that peers can connect with WebRTC, but you can increase the probably by using a TURN server and passing the details into `new WebTorrent({ tracker: { rtcConfig: { /* config here */ }}})`
