### ISSUE TITLE
Do I need to manually specify tracker?

### ISSUE THREAD

**Issue by singpolyma** [feross/webtorrent-hybrid#35]
https://github.com/feross/webtorrent/issues/288 indicates that there is no DHT yet for the webtorrent side.  So, do I need to manually add a webtorrent tracker to my magnet link so that instant.io and others can find my peers?  Or will the CLI add one for me?

**Comment by DiegoRBaquero** [comment]
Default ones are provided if none is specified. https://github.com/feross/create-torrent/blob/master/index.js#L10-L13

**Comment by singpolyma** [comment]
That's for creating a new torrent -- what about seeding one I've downloaded?

**Comment by DiegoRBaquero** [comment]
WebTorrent core adds default webrtc trackers for downloading/seeding when none are specified.

If you use `webtorrent seed` command, it does create a torrent from the provided files. If you try to seed a magnet or .torrent, it will do a download process.

**Comment by feross** [comment]
If you want to seed an existing .torrent, the way to do it is to use `client.add` and pass in the right `path` option to where the file(s) are saved (the client will verify the files and not re-download the torrent).
