### ISSUE TITLE
Using webtorrent-hybrid to download from another webtorrent-hybrid seeding using WebRTC(electron-webrtc)

### ISSUE THREAD

**Issue by dennischang** [feross/webtorrent-hybrid#37]
Hi Feross,

First of all, thanks for this amazing project.

Currently, I am using webtorrent-hybrid to seeding in node.js/Mac (also tested on Ubuntu with xvfb). I can download the files using instant.io or Desktop, but not from another webtorrent-hybrid node.js process.

But if I opened instant.io to download the same seed, the webtorrent-hybrid node.js download process start working. Once I close the browser (instant.io), the downloading process stopped too.

Any advice? Thank you!
Dennis

**Comment by dennischang** [comment]
Seems like the createOffer always get wrong localDescription information, ex:

{"type":"offer","sdp":"v=0\r\no=- 6468117243632312017 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:UWoyQg/X7rA5ltUg\r\na=ice-pwd:Iu3QnJGUrL+cbpF08OQAr1tq\r\na=fingerprint:sha-256 2A:FD:61:AD:4E:CD:8E:41:FB:4A:FE:E8:F3:C0:79:71:50:83:79:A3:56:4F:87:AC:DA:E1:CF:8D:C5:38:AA:0A\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}

**Comment by dennischang** [comment]
It works after update a few codes in [RTCPeerConnection.js](https://github.com/dennischang/electron-webrtc/commit/3d5a8b120afad6d854e9982cbcb8b2caa5c4ebb8#diff-dee4e02a0eb468ebd6569980698617d1), FYR

Only tested on my OS X, need further testing in different platform ...

**Comment by pietrovismara** [comment]
Same problem here, i'm seeding with Nodejs with Webtorrent-hybrid 1.0.3 and in the `seedOptions.announceList` i keep only the ws address of the tracker.
If i download using webtorrent via browser it works, but via Nodejs WebTorrent-hybrid it doesn't.
Both clients send the start event to bittorrent-tracker but the peers are not connecting.

If instead i allow http too in `seedOptions.announceList` it works. 
Is this correct or a bug?
@dennischang **TL:DR** Try to add the http address of the tracker in `seedOptions.announceList`.

**Comment by dennischang** [comment]
@pietrovismara Did you seeding and download in different network using node.js with webtorrent-hybrid?

My test results:
(1) Node.js --> Browser (WAN ok, Lan ok)
(2) Browser --> Node.js (WAN ok, Lan ok)
(3) Node.js --> Node.js (WAN failed, Lan ok)

PS: WAN means peers are in different network.

For the scenario 3, both sides get correct port mapping information from ice server, but just can not connect to each other. I also tried to enabled turn server, not working ....

Dennis

**Comment by pietrovismara** [comment]
@dennischang Nope for now just testing multiple istances on my laptop.

**Comment by feross** [comment]
@dennischang If you think there's a bug in `electron-webrtc`, then please send a PR. I'm sure @mappum would appreciate that.
