### ISSUE TITLE
Looks like electron-eval is failing

### ISSUE THREAD

**Issue by rllola** [feross/webtorrent-hybrid#45]
Hi,

I am trying to make webtorrent-hybrid work on a server but whatever I do I have this error. What is more frustrating is that a couple of days ago it was working but then I erase everything for a fresh install...

Here the error : 
```
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.5.0, webtorrent 0.96.4, node v4.4.5, linux x64, exit 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: electron-eval error: Electron process exited with code 0.
Stderr:
Xlib:  extension "RANDR" missing on display ":100".
Xlib:  extension "RANDR" missing on display ":100".


    at ChildProcess.<anonymous> (/usr/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/node_modules/electron-eval/lib/index.js:145:30)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

I have install Xvfb and its dependencies. I also have run the prepareHeadless script.

**Comment by DiegoRBaquero** [comment]
See if this helps: http://stackoverflow.com/questions/17944234/xlib-extension-randr-missing-on-display-21-trying-to-run-headless-googl

**Comment by rllola** [comment]
I tried but it doesn't change anything.

**Comment by rllola** [comment]
With the webtorrent-cli it does work with sintel but with webtorrent-hybrid it crash.

**Comment by DiegoRBaquero** [comment]
I'm currently getting the same error on Ubuntu 14.04

**Comment by rllola** [comment]
I don't have this issue anymore. I believe that the realease of `electron-eval 0.9.5` fixed this problem.
