### ISSUE TITLE
Example does not work on Node

### ISSUE THREAD

**Issue by kevgathuku** [feross/webtorrent-hybrid#49]
Node Version: 6.9.1

Hi, 
I am trying to run the `node-download.js` script provided in the examples directory and I am constantly getting this error: 

```/torrent/node_modules/simple-peer/index.js:59
      throw new Error('No WebRTC support: Specify `opts.wrtc` option in this environment')
```

Any help on how to proceed would be greatly appreciated.

**Comment by feross** [comment]
Glad you got this figured out
