### ISSUE TITLE
Reflections on the user's firewall?

### ISSUE THREAD

**Issue by s-a** [feross/webtorrent-hybrid#50]
First of all thanks for sharing this library. It works all out of the box and I was able to create a serverless website with node and crome in a few minutes. I d like to ask. Do there exist considerations for the web site visitors firewall which blocks webtorrent' s communication?

**Comment by feross** [comment]
Yes, WebRTC takes care of NAT hole punching for you. I recommend reading https://www.html5rocks.com/en/tutorials/webrtc/basics/#toc-signaling and also reading about STUN and TURN.

Especially if you want to guarantee reliable delivery of your torrent, consider using either a web seed (an http server that hosts the torrent contents) or a TURN server (a centralized endpoint that both peers can connect to if they can't connect directly to each other).
