### ISSUE TITLE
error command not found cli for --on-done

### ISSUE THREAD

**Issue by Rakesh-phpdeveloper** [feross/webtorrent-hybrid#54]
for debug info
npm version : 2.15.9
webtorrent-hybrid  version : 1.6.0 (0.97.2)
error : --on-done: command not found
I also installed the webtorrent cli

command used : webtorrent-hybrid magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.io&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4 --on-done node.js

here i used simple node js script saying console.log("This is node js");

Here once the torrent has been downloaded, I'm trying to run my own script. Here torrent file is downloaded but the script is excecuted. I don't n know what is the issue here. cli shows --on-done: command not found.
I also installed the webtorrent cli. Same problem exists.

**Comment by feross** [comment]
The command you pass to `--on-done` has to be a valid command that you could run on the command line.

So, try this instead: `--on-done="node node.js"`
