### ISSUE TITLE
No luck trying on CentOS or Ubuntu

### ISSUE THREAD

**Issue by ducdigital** [feross/webtorrent-hybrid#56]
Hello,

I am trying to spawn a seed server to stream data, however, `webtorrent-hybrid` always suck at fetching torrent metadata and does not switch to the download screen no matter how long I waited.

Tested on both ubuntu and centOS. Tested with `webtorrent` and `webtorrent-hybrid` CLI

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/1712140/21589482/88832cf8-d0f2-11e6-9398-498b49434720.png)

What would be the problem for this? on OSX everything works perfectly

**Comment by feross** [comment]
I think you need to put quotes around the magnet link.
