### ISSUE TITLE
Not Seeding after download

### ISSUE THREAD

**Issue by sunilrx** [feross/webtorrent-hybrid#57]
Hi,
When i run the webtorrent hybrid  command it does not seed after downloading.
Command:  webtorrent-hybrid "magnet-url" --keep-seeding

"torrent downloaded successfully from 39/50 peers in 71s!
webtorrent is exiting..."

I would like to continue seeding even after downloading the file.

**Comment by feross** [comment]
What do you get when you run `webtorrent-hybrid --version`?

**Comment by feross** [comment]
Also, are you running with any extra flags, like for example the `--vlc` flag for streaming? Because if you do, then webtorrent will automatically quit when VLC is closed.

**Comment by feross** [comment]
In fact, I just looked at the code again and I think that you must have a streaming option. I see no other way that webtorrent would automatically quit.
