### ISSUE TITLE
specify specific versions of dependencies

### ISSUE THREAD

**Issue by ericwooley** [feross/webtorrent-hybrid#6]
wRTC is broken in node 0.12 in wRTC, and when I used a computer with that node version on it, everything broke. Specifying 0.0.55 fixed the issue.

**Comment by feross** [comment]
The latest version of wrtc (0.0.56) works fine for me on OS X and node 0.12.3. I'm not sure why installing 0.0.55 fixed your problem. Any ideas?

**Comment by ericwooley** [comment]
I am not really sure, I found this issue https://github.com/js-platform/node-webrtc/issues/190 and assumed that was what was affecting me.  It says the tests fail intermittently on travis, so maybe you are on an up and I am on a down. It was working for me yesterday, but I just switched to nvm@stable and it stopped working. Not sure what the deal is, hopefully they figure it out soon, but I would stick with 55, until then

**Comment by feross** [comment]
Thanks for the pointed to that issue. It looks rather old. It was made when 0.0.55 was the current stable version. 0.0.56 shouldn't make things any worse.

What do you mean you switched to nvm@stable? Did that change your version of node? Because that will always cause native addons like wrtc to break until they're re-compiled with `npm rebuild` or installed from scratch with `npm install`.

**Comment by ericwooley** [comment]
Yea I did change version of node, but I removed node_modules and npm installed. I also tried from a vagrant box, you can check my setup here https://github.com/ericwooley/streamChunkVM/blob/master/video-streamer.js. It's possible I am doing something weird. 

IIRC, it was saying that it couldn't resolve wrtc at all. I tried rebuilding a couple times, in unix and OSX, to no avail. Changing the version number solved the issue. Now that I think about it though, that issue might not have anything to do with why it wouldn't import. I think it built fine. 

I'll try installing the latest again and see if it works, it's a bummer it takes so long.

**Comment by ericwooley** [comment]
It's working now, awesome? (I much prefer if it worked or didn't work)

Anyways, feel free to close the issue if you like. Really more of a suggestion than an issue.

**Comment by feross** [comment]
What we really need to do is make wrtc more reliable, or start using electron-spawn for WebRTC (https://github.com/feross/webtorrent-hybrid/issues/5) since these build issues come up all the time.

**Comment by feross** [comment]
@ericwooley Turns out you were right, v0.0.56 of wrtc was causing issues. I've locked to v0.0.55 for now to resolve the issue.

See https://github.com/js-platform/node-webrtc/issues/212
