### ISSUE TITLE
port?

### ISSUE THREAD

**Issue by chovy** [feross/webtorrent-hybrid#63]
Seems my firewall is blocking communcation, what port does this use?
6881 does not work as those are allowed by my firewall.

i tried `--port 8071` flag which is open in firewall too for tcp 

It works fine locally but not on server. for example I can use webtorrent-hybrid locally and seed and then load webtorrent in the browser and it will load the video. But when I run webtorrent-hybrid on a server it is not connecting to my local browser client.

I did notice on my mac I have to Allow Incoming connections (from electron). Is that being triggered on the server? Is there an option to click "Allow Incoming Connections"?

**Comment by feross** [comment]
The `--port` option is only used to specify the TCP listening port for normal torrent connections. WebRTC works differently. Internally, WebRTC uses a process called ICE which picks a random port for each connection. There is no way to configure it.

**Comment by chovy** [comment]
Hey Feross. How does webrtc on my desktop browser get through my residential firewall without me allowing incoming connections for all ports?

**Comment by feross** [comment]
WebRTC uses [ICE](https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment) and [STUN](https://en.wikipedia.org/wiki/STUN) to poke a hole in your NAT/firewall.
