### ISSUE TITLE
thread monstrous xD

### ISSUE THREAD

**Issue by kocoten1992** [feross/webtorrent-hybrid#64]
I use this code:
```
node_modules/.bin/webtorrent-hybrid seed data/my_movie.mp4 --announce 'ws://example.com:6881/announce'
```

And let it work for a while, number of thread jump from 700 (my normal number of thread of every day usage Ubuntu desktop) to 4k6 threads xD, when do ctrl - c, it go back to normal ~700, will try dig into code and report here.

**Comment by feross** [comment]
This library uses `electron-webrtc` under the hood for it's WebRTC implementation. This is not a very efficient library as it basically starts an entire instance of Chrome. Sorry, no way to fix this until there's a better WebRTC library in Node.js that we can switch to.
