### ISSUE TITLE
 webtorrent-hybrid crash with babelify

### ISSUE THREAD

**Issue by uriylla** [feross/webtorrent-hybrid#65]
using babelify, webtorrent-hybrid crashes due to a missing module dependency

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'spawn-sync' from '.../node_modules/webtorrent-hybrid/node_modules/electron-webrtc/node_modules/electron-eval/node_modules/cross-spawn'

it also crashes sometimes with the missing dependency 'child-killer' which is kind of dead if I'm not mistaken.

Cannot find module 'child-killer' from '.../node_modules/webtorrent-hybrid/node_modules/electron-webrtc/node_modules/electron-eval/node_modules/headless'

I guess it's some issue with the webtorrent-hybrid module with babelify, since using the normal webtorrent module with the same code is not crashing for me, but the torrents are not being downloaded since I'm using node.js and electron.

**Comment by feross** [comment]
Why are you running babel on `webtorrent-hybrid`? If you're trying to run webtorrent in the browser, you should use the `webtorrent` package.

`webtorrent-hybrid` is just the `webtorrent` package, plus a native webrtc implementation for Node.js.

If you're running in Electron, you can use the normal `webtorrent` package just fine. Electron renderer processes have access to Node.js APIs (for TCP and UDP) and browsers APIs (for WebRTC).

**Comment by uriylla** [comment]
@feross 

Thank you for your answer.

Yes, at first I tried with the `webtorrent` package, but the torrents added to the client doesn't seem to connect to any WebRTC peer. The downloads won't start after the metadata is downloaded.

On a previous version without running babel the `webtorrent-hybrid` package did just fine.

**Comment by uriylla** [comment]
@feross 

Thank you for your answer.

Yes, first I tried the `webtorrent` package, but when adding a torrent to the client it doesn't seem to connect to any WebRTC peer... After the ready event of the torrent it doesn't download anything

On a previous version without running babel I used the `webtorrent-hybrid` and it did just fine, with basically the same code.

I don't know what I might be doing wrong.

**Comment by feross** [comment]
If you're running webtorrent in the browser, then you want `webtorrent`, not `webtorrent-hybrid`. The extra stuff in `webtorrent-hybrid` cannot actually run in the browser environment – it's all native code.

Are you running in Node.js or the browser?

**Comment by uriylla** [comment]
Yes I'm using it in the renderer process, but it doesn't seem to connect to any WebRTC peers.

my code looks like this
```

import EventEmitter from 'events'
import player from '../window/player/player-controller'
import WebTorrent from 'webtorrent'

class TorrentManager extends EventEmitter {

  constructor () {
    super()
    this._client = new WebTorrent()
  }

  startStream (magnetUri) {
    this._client.add(magnetUri, function (torrent) {
      const interval = setInterval(() => {
        console.log('Progress: ' + (torrent.progress * 100).toFixed(1) + '%'+ '  -  Speed: ' + torrent.downloadSpeed + '  -  Peers: ' + torrent.numPeers)
      }, 1000)
      torrent.files.forEach((file) => {
        const filetype = file.name.substr(file.name.lastIndexOf('.') + 1)
        if (filetype === 'mp4') player.playStream(file)
      })
      torrent.on('done', function () {
        clearInterval(interval)
      })
    })
  }

}

export default new TorrentManager()

```

always outputs 

> 
Progress: 0.0%  -  Speed: 0  -  Peers: 0

**Comment by uriylla** [comment]
@feross, okay I tried with the webtorrent's exmaple [sintel.torrent](https://webtorrent.io/torrents/sintel.torrent) and it works just fine. I don't know why any other torrent that downloads normally on any other client is not being downloaded in my app...

just to clarify, I'm using the `webtorrent` package in the renderer process of electron, with the code shown above.

**Comment by feross** [comment]
From the [FAQ](https://webtorrent.io/faq):

> Why does browser downloading not work? I see no peers!

> It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. WebTorrent Desktop, Vuze, webtorrent-hybrid, Playback, instant.io, or βTorrent.

> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.

**Comment by uriylla** [comment]
But the links I'm using are valid. 
In fact i tried them in Webtorrent Desktop and they are being downloaded.

**Comment by DiegoRBaquero** [comment]
> In the browser, WebTorrent can only download torrents that are **explicitly** seeded to web peers via a WebRTC-capable client

**Comment by uriylla** [comment]
Finally I found a workaround that solved my issue.
I simply didn't run babel on the file that uses the `webtorrent` package.

Sorry for this issue should have been posted in the webtorrent repo.

**Comment by adamwoo2444** [comment]
@uriylla  can you help me I am facing same issue.
