### ISSUE TITLE
Seed a file via WebTorrent while downloading it via BitTorrent

### ISSUE THREAD

**Issue by hezag** [feross/webtorrent-hybrid#8]
Hi, @feross,
Is it technically possible to seed a file (or pieces of it) via WebTorrent while downloading it from BitTorrent?

**Comment by feross** [comment]
Yes, that is exactly how `webtorrent-hybrid` is supposed to work!

However there's a bug with connecting to normal, non-web peers: https://github.com/feross/webtorrent/issues/310#issue-74746314 Once this bug is fixed, then `webtorrent-hybrid` will work as designed.
